#!/bin/bash

if [ "${BASH_SOURCE[0]}" -ef "$0" ]
then
    echo -e "\nERROR: This script must be sourced not executed!\n"
    exit 1
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

export PATH=$SCRIPT_DIR/bin:$PATH

